apiVersion: v1
kind: Pod
metadata:
  name: solar-system
  labels:
    app: solar-system-app
spec:
  containers:
    - name: solar-system
      image: nooli/solar-system:25.08.60
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  labels:
    app: solar-system-app
spec:
  type: NodePort
  selector:
    app: solar-system-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020
